### ISSUE TITLE
Retravailler la palette de couleurs pour les pseudos

### ISSUE THREAD

**Issue by CaptaiNapalm** [CaptaiNapalm/aria#6]
Avoir une dizaine de couleurs shiny et les distribuer aléatoirement par nouveaux pseudos, de tel sorte que tant que le nombre de couleurs n'a pas été totalement distribués, il ne peut y avoir deux fois la même couleur

**Comment by kolinhar** [comment]
Je propose cette palette de 11 couleurs 
![couleurs shiny test 1](https://cloud.githubusercontent.com/assets/5618440/18579750/d56b0c8e-7bf7-11e6-931b-44f0bc559f85.jpg)

**Comment by CaptaiNapalm** [comment]
Essayons avec ceci, au mieux on garde tel quel, au pire on aura simplement à changer les codes couleurs ^^

**Comment by CaptaiNapalm** [comment]
Implémenter par le commit 649b65dad1e5208f3a5fa0efca43c73482229739
GG!
