### ISSUE TITLE
Plus de notifs HTML5

### ISSUE THREAD

**Issue by CaptaiNapalm** [CaptaiNapalm/aria#7]
Depuis la dernière pull request, les notifs HTML5 ne s'affichent plus.

**Comment by kolinhar** [comment]
les notifs semblent ne plus s'afficher sous Chrome, mais fonctionnent avec Firefox.

**Comment by CaptaiNapalm** [comment]
Fix via commit 713b0f92d5ed06e0449ddbfde34ac128e40a7dae
